# Site Settings
title: Store Front
email: ls724310@gmail.com
description: >
  A sweet store front for a baller seller.
baseurl: "/"
url: ""
twitter_username:
github_username:  lmstroop
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
navigation:
- text: About
  url: /about/
- text: Projects
  url: /projects/
  layout: project
- text: Crafts
  url: /crafts/
- text: Pets
  url: /pets/
